
import type { Plant } from "@/models";
import { Timestamp } from "firebase/firestore";

// Note: This mock data is illustrative. 
// Timestamps are hardcoded for simplicity in mocks, but Firestore uses serverTimestamp().
const mockTimestamp = Timestamp.now();

export const mockPlants: Plant[] = [
  {
    id: "1",
    name: "Monstera Deliciosa",
    description: "Large, healthy Monstera with beautiful fenestrations. Easy to care for.",
    imageUrls: ["/plant-images/monstera.jpg"],
    imageHints: ["monstera plant"],
    price: 45,
    type: "sale",
    sellerId: "mockSeller123",
    sellerName: "PlantLover123",
    location: "San Francisco, CA",
    tags: ["For Sale", "Easy Care", "Popular"],
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "2",
    name: "Ariocarpus F2 Fiss. x Lloydii ",
    description: "Beautiful Ariocarpus received from Big Cactus. Huge Root.",
    imageUrls: ["/plant-images/ariocarpus.jpeg"],
    imageHints: ["ariocarpus"],
    type: "trade",
    sellerId: "mockSeller456",
    sellerName: "GreenThumbSF",
    location: "Oakland, CA",
    tags: ["For Trade", "High Light"],
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "3",
    name: "Annie x Bert Variegated Trichocereus Hybrid",
    description: "Annie x Bert with one yellow pup and one green pup. Open to sale and trade!",
    imageUrls: ["/plant-images/AnniexBert.jpeg"],
    imageHints: ["AnniexBert Graft"],
    price: 50,
    type: "sale_trade",
    sellerId: "mockSeller789",
    sellerName: "IvyLeague",
    location: "Berkeley, CA",
    tags: ["For Sale", "For Trade", "Graft", "Beginner Friendly"],
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "4",
    name: "Ecuadorian Pachanoi",
    description: "Stunning Ecuadorian Pachanoi Stand Needs bright, direct light.",
    imageUrls: ["/plant-images/pach.jpeg"],
    imageHints: ["pach"],
    price: 70,
    type: "sale",
    sellerId: "mockSeller101",
    sellerName: "PachMan",
    location: "San Jose, CA",
    tags: ["For Sale", "Statement Plant", "Bright Light"],
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "5",
    name: "Bridgesii cv. Yehuda",
    description: "Rarely offereed Bridgesii with lots of girth. Get absolutely MASSIVE!",
    imageUrls: ["/plant-images/yehuda.jpeg"],
    imageHints: ["yehuda"],
    type: "trade",
    sellerId: "mockSeller202",
    sellerName: "SucculentKing",
    location: "Palo Alto, CA",
    tags: ["For Trade", "Trichocereus", "Cacti"],
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "6",
    name: "ZZ Plant",
    description: "Hardy ZZ Plant, perfect for beginners. Tolerates low light.",
    imageUrls: ["/plant-images/zz.jpg"],
    imageHints: ["zz plant"],
    price: 30,
    type: "sale",
    sellerId: "mockSeller303",
    sellerName: "EasyGreens",
    location: "Fremont, CA",
    tags: ["For Sale", "Drought Tolerant", "Low Maintenance"],
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "7",
    name: "Spider Plant",
    description: "Classic Spider Plant with many plantlets. Easy to propagate.",
    imageUrls: ["/plant-images/spiderplant.jpg"],
    imageHints: ["spider plant"],
    price: 15,
    type: "sale_trade",
    sellerId: "mockSeller404",
    sellerName: "WebOfPlants",
    location: "Daly City, CA",
    tags: ["For Sale", "For Trade", "Easy to Propagate", "Pet Friendly"],
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "8",
    name: "Calathea Orbifolia",
    description: "Beautiful Calathea Orbifolia with large, striped leaves. Loves humidity.",
    imageUrls: ["/plant-images/Calathea.jpg"],
    imageHints: ["calathea plant"],
    type: "trade",
    sellerId: "mockSeller505",
    sellerName: "PrayerPlantsGalore",
    location: "Walnut Creek, CA",
    tags: ["For Trade", "Prayer Plant", "Humidity Lover"],
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
];
